"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var StyledArrowsMergeAltV = styled_components_1.default.i(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  &{box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:12px;height:22px;background:linear-gradient(to left,currentColor 10px,transparent 0)no-repeat center top/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat center bottom/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat center 20px/10px 2px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat center 0/10px 2px}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:6px;height:6px;transform:rotate(45deg);left:3px}&::after{border-left:2px solid;border-top:2px solid;bottom:3px;}&::before{border-right:2px solid;border-bottom:2px solid;top:3px}\n"], ["\n  &{box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:12px;height:22px;background:linear-gradient(to left,currentColor 10px,transparent 0)no-repeat center top/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat center bottom/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat center 20px/10px 2px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat center 0/10px 2px}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:6px;height:6px;transform:rotate(45deg);left:3px}&::after{border-left:2px solid;border-top:2px solid;bottom:3px;}&::before{border-right:2px solid;border-bottom:2px solid;top:3px}\n"])));
exports.ArrowsMergeAltV = react_1.default.forwardRef(function (props, ref) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(StyledArrowsMergeAltV, tslib_1.__assign({}, props, { ref: ref, "icon-role": "arrows-merge-alt-v" }))));
});
var templateObject_1;
//# sourceMappingURL=ArrowsMergeAltV.js.map