"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var StyledArrowsMergeAltH = styled_components_1.default.i(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  &{box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:22px;height:12px;background:linear-gradient(to left,currentColor 12px,transparent 0)no-repeat center left/8px 2px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat center right/8px 2px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat 20px center/2px 12px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat 0 center/2px 12px}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:6px;height:6px;transform:rotate(45deg);top:3px}&::after{border-left:2px solid;border-bottom:2px solid;right:3px;}&::before{border-right:2px solid;border-top:2px solid;left:3px}\n"], ["\n  &{box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:22px;height:12px;background:linear-gradient(to left,currentColor 12px,transparent 0)no-repeat center left/8px 2px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat center right/8px 2px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat 20px center/2px 12px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat 0 center/2px 12px}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:6px;height:6px;transform:rotate(45deg);top:3px}&::after{border-left:2px solid;border-bottom:2px solid;right:3px;}&::before{border-right:2px solid;border-top:2px solid;left:3px}\n"])));
exports.ArrowsMergeAltH = react_1.default.forwardRef(function (props, ref) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(StyledArrowsMergeAltH, tslib_1.__assign({}, props, { ref: ref, "icon-role": "arrows-merge-alt-h" }))));
});
var templateObject_1;
//# sourceMappingURL=ArrowsMergeAltH.js.map