"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var StyledAttribution = styled_components_1.default.i(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  &{display:block;box-sizing:border-box;transform:scale(var(--ggs,1));width:16px;height:18px;background:linear-gradient(to left,currentColor 14px,transparent 0) no-repeat 1px 2px/8px 2px,linear-gradient(to left,currentColor 14px,transparent 0) no-repeat 6px 14px/6px 2px,radial-gradient(circle,currentColor 60%,transparent 40%) no-repeat 10px 12px/6px 6px,radial-gradient(circle,currentColor 60%,transparent 40%) no-repeat 0 0/6px 6px}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:8px;height:8px;border:2px solid}&::before{border-right:0;border-top-left-radius:10px;border-bottom-left-radius:10px;top:8px;left:2px}&::after{border-left:0;border-top-right-radius:10px;border-bottom-right-radius:10px;right:2px;top:2px}\n"], ["\n  &{display:block;box-sizing:border-box;transform:scale(var(--ggs,1));width:16px;height:18px;background:linear-gradient(to left,currentColor 14px,transparent 0) no-repeat 1px 2px/8px 2px,linear-gradient(to left,currentColor 14px,transparent 0) no-repeat 6px 14px/6px 2px,radial-gradient(circle,currentColor 60%,transparent 40%) no-repeat 10px 12px/6px 6px,radial-gradient(circle,currentColor 60%,transparent 40%) no-repeat 0 0/6px 6px}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:8px;height:8px;border:2px solid}&::before{border-right:0;border-top-left-radius:10px;border-bottom-left-radius:10px;top:8px;left:2px}&::after{border-left:0;border-top-right-radius:10px;border-bottom-right-radius:10px;right:2px;top:2px}\n"])));
exports.Attribution = react_1.default.forwardRef(function (props, ref) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(StyledAttribution, tslib_1.__assign({}, props, { ref: ref, "icon-role": "attribution" }))));
});
var templateObject_1;
//# sourceMappingURL=Attribution.js.map