"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var StyledCast = styled_components_1.default.i(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  &{background:linear-gradient( to left,currentColor 5px,transparent 0)no-repeat bottom right/6px 2px,linear-gradient( to left,currentColor 5px,transparent 0)no-repeat top left/2px 2px;box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:20px;height:16px;border-top:2px solid;border-right:2px solid;border-radius:2px;border-left:0}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:20px;height:20px;border:6px double;border-top-color:transparent;border-bottom-color:transparent;border-left-color:transparent;border-radius:50%;transform:rotate(-45deg);bottom:-10px;left:-10px}&::after{width:4px;height:4px;border:2px solid;border-top-color:transparent;border-bottom-color:transparent;border-left-color:transparent;bottom:-2px;left:-2px}\n"], ["\n  &{background:linear-gradient( to left,currentColor 5px,transparent 0)no-repeat bottom right/6px 2px,linear-gradient( to left,currentColor 5px,transparent 0)no-repeat top left/2px 2px;box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:20px;height:16px;border-top:2px solid;border-right:2px solid;border-radius:2px;border-left:0}&::after,&::before{content:\"\";display:block;box-sizing:border-box;position:absolute;width:20px;height:20px;border:6px double;border-top-color:transparent;border-bottom-color:transparent;border-left-color:transparent;border-radius:50%;transform:rotate(-45deg);bottom:-10px;left:-10px}&::after{width:4px;height:4px;border:2px solid;border-top-color:transparent;border-bottom-color:transparent;border-left-color:transparent;bottom:-2px;left:-2px}\n"])));
exports.Cast = react_1.default.forwardRef(function (props, ref) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(StyledCast, tslib_1.__assign({}, props, { ref: ref, "icon-role": "cast" }))));
});
var templateObject_1;
//# sourceMappingURL=Cast.js.map