"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var StyledComponents = styled_components_1.default.i(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  &{box-sizing:border-box;position:relative;display:block;transform:rotate(45deg)scale(var(--ggs,1));width:14px;height:14px;background:linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 0 0/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 4px 0/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 8px 0/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 12px 0/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 0 8px/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 4px 8px/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 8px 8px/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 12px 8px/2px 6px}&::after,&::before{content:\"\";display:block;position:absolute;width:6px;height:2px;border-top:6px double;border-bottom:6px double}&::after{right:0}\n"], ["\n  &{box-sizing:border-box;position:relative;display:block;transform:rotate(45deg)scale(var(--ggs,1));width:14px;height:14px;background:linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 0 0/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 4px 0/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 8px 0/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 12px 0/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 0 8px/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 4px 8px/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 8px 8px/2px 6px,linear-gradient(to left,currentColor 10px,transparent 0)no-repeat 12px 8px/2px 6px}&::after,&::before{content:\"\";display:block;position:absolute;width:6px;height:2px;border-top:6px double;border-bottom:6px double}&::after{right:0}\n"])));
exports.Components = react_1.default.forwardRef(function (props, ref) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(StyledComponents, tslib_1.__assign({}, props, { ref: ref, "icon-role": "components" }))));
});
var templateObject_1;
//# sourceMappingURL=Components.js.map