"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var StyledDirectory = styled_components_1.default.i(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  & {\n    background: linear-gradient(to left, currentColor 5px, transparent 0) no-repeat 2px 2px/4px 2px,\n      linear-gradient(to left, currentColor 5px, transparent 0) no-repeat 2px 6px/4px 2px,\n      linear-gradient(to left, currentColor 5px, transparent 0) no-repeat 2px 10px/4px 2px;\n    display: block;\n    transform: scale(var(--ggs, 1));\n    width: 22px;\n    height: 18px;\n    box-sizing: border-box;\n    border-radius: 3px;\n    border: 2px solid;\n    position: relative;\n    margin-left: -2px;\n  }\n  &::after,\n  &::before {\n    content: '';\n    display: block;\n    box-sizing: border-box;\n    position: absolute;\n    border: 2px solid;\n  }\n  &::before {\n    top: 2px;\n    border-radius: 100px;\n    right: 4px;\n    width: 5px;\n    height: 5px;\n  }\n  &::after {\n    width: 9px;\n    height: 4px;\n    border-radius: 150px;\n    border-bottom-left-radius: 0;\n    border-bottom-right-radius: 0;\n    border-bottom: 0;\n    right: 2px;\n    bottom: 2px;\n  }\n"], ["\n  & {\n    background: linear-gradient(to left, currentColor 5px, transparent 0) no-repeat 2px 2px/4px 2px,\n      linear-gradient(to left, currentColor 5px, transparent 0) no-repeat 2px 6px/4px 2px,\n      linear-gradient(to left, currentColor 5px, transparent 0) no-repeat 2px 10px/4px 2px;\n    display: block;\n    transform: scale(var(--ggs, 1));\n    width: 22px;\n    height: 18px;\n    box-sizing: border-box;\n    border-radius: 3px;\n    border: 2px solid;\n    position: relative;\n    margin-left: -2px;\n  }\n  &::after,\n  &::before {\n    content: '';\n    display: block;\n    box-sizing: border-box;\n    position: absolute;\n    border: 2px solid;\n  }\n  &::before {\n    top: 2px;\n    border-radius: 100px;\n    right: 4px;\n    width: 5px;\n    height: 5px;\n  }\n  &::after {\n    width: 9px;\n    height: 4px;\n    border-radius: 150px;\n    border-bottom-left-radius: 0;\n    border-bottom-right-radius: 0;\n    border-bottom: 0;\n    right: 2px;\n    bottom: 2px;\n  }\n"])));
exports.Directory = react_1.default.forwardRef(function (props, ref) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(StyledDirectory, tslib_1.__assign({}, props, { ref: ref, "icon-role": "directory" }))));
});
var templateObject_1;
//# sourceMappingURL=Directory.js.map