"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var StyledShoppingCart = styled_components_1.default.i(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  &{display:block;box-sizing:border-box;position:relative;transform:scale(var(--ggs,1));width:20px;height:21px;background:linear-gradient(to left,currentColor 12px,transparent 0)no-repeat -1px 6px/18px 2px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat 6px 14px/11px 2px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat 0 2px/4px 2px,radial-gradient(circle,currentColor 60%,transparent 40%)no-repeat 12px 17px/4px 4px,radial-gradient(circle,currentColor 60%,transparent 40%)no-repeat 6px 17px/4px 4px}&::after,&::before{content:\"\";display:block;position:absolute;box-sizing:border-box;width:2px;height:14px;background:currentColor;top:2px;left:4px;transform:skew(12deg)}&::after{height:10px;top:6px;left:16px;transform:skew(-12deg)}\n"], ["\n  &{display:block;box-sizing:border-box;position:relative;transform:scale(var(--ggs,1));width:20px;height:21px;background:linear-gradient(to left,currentColor 12px,transparent 0)no-repeat -1px 6px/18px 2px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat 6px 14px/11px 2px,linear-gradient(to left,currentColor 12px,transparent 0)no-repeat 0 2px/4px 2px,radial-gradient(circle,currentColor 60%,transparent 40%)no-repeat 12px 17px/4px 4px,radial-gradient(circle,currentColor 60%,transparent 40%)no-repeat 6px 17px/4px 4px}&::after,&::before{content:\"\";display:block;position:absolute;box-sizing:border-box;width:2px;height:14px;background:currentColor;top:2px;left:4px;transform:skew(12deg)}&::after{height:10px;top:6px;left:16px;transform:skew(-12deg)}\n"])));
exports.ShoppingCart = react_1.default.forwardRef(function (props, ref) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(StyledShoppingCart, tslib_1.__assign({}, props, { ref: ref, "icon-role": "shopping-cart" }))));
});
var templateObject_1;
//# sourceMappingURL=ShoppingCart.js.map