"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var StyledTikcode = styled_components_1.default.i(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  &{box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:18px;height:18px;background:linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 10px 0/8px 2px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 10px 6px/8px 2px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 10px 10px/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 13px 10px/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 16px 10px/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 16px 0/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 10px 0/2px 8px}&::after,&::before{content:\"\";position:absolute;display:block;box-sizing:border-box;width:8px;height:8px;border:2px solid}&::after{bottom:0}\n"], ["\n  &{box-sizing:border-box;position:relative;display:block;transform:scale(var(--ggs,1));width:18px;height:18px;background:linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 10px 0/8px 2px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 10px 6px/8px 2px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 10px 10px/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 13px 10px/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 16px 10px/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 16px 0/2px 8px,linear-gradient(to left,currentColor 10px,transparent 0) no-repeat 10px 0/2px 8px}&::after,&::before{content:\"\";position:absolute;display:block;box-sizing:border-box;width:8px;height:8px;border:2px solid}&::after{bottom:0}\n"])));
exports.Tikcode = react_1.default.forwardRef(function (props, ref) {
    return (react_1.default.createElement(react_1.default.Fragment, null,
        react_1.default.createElement(StyledTikcode, tslib_1.__assign({}, props, { ref: ref, "icon-role": "tikcode" }))));
});
var templateObject_1;
//# sourceMappingURL=Tikcode.js.map